# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = Ubuntu Nerd Font

general {
    hide_cursor = false
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/Pictures/Wallpapers/wallhaven-5y5w71_3440x1440.png
    # path = ~/Pictures/Wallpapers/fedora_day.png
    blur_passes = 2
}

input-field {
    monitor =
    size = 550, 55
    outline_thickness = 2
    # inner_color = rgba(0, 0, 0, 0.0) # no fill
    # inner_color = rgba(36, 40, 59, 1)
    # inner_color = rgba(24283bee)
    # inner_color = rgba(20, 23, 29, 0.5)
    inner_color = rgba(0, 0, 0, 0.4)
    outer_color = rgba(0, 0, 0, 0.4)

    # outer_color = rgba(0, 0, 0, 0.4)
    # outer_color = rgba(c0caf5ee)
    # outer_color = rgba(255, 255, 255, 1)
    check_color = rgba(999999ee) 
    fail_color = rgba(e29494ee) 

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 10

    # font_family = $font
    placeholder_text = 
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -80
    halign = center
    valign = center
}

# 
label {
    monitor =
    text = ㅤㅤ
    font_size = 30

    position = 0, 225
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME12 # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 60
    # font_family = $font

    position = 0, 50 
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B" # update every 60 seconds
    font_size = 25
    # font-family = $font

    position = 0, 150
    halign = center
    valign = center
}

# POWER
label {
    monitor =
    text = cmd[update:60000] ~/.config/hypr/scripts/check_power.sh
    font_size = 15

    position = -30, -10
    halign = right
    valign = top
}

# NETWORK 
label {
    monitor = 
    text = cmd[update:60000] ~/.config/hypr/scripts/check_network.sh
    font_size = 15 

    position = -125, -10
    halign = right
    valign = top
}

label {
    monitor =
    text = 
    # text = $LAYOUT[en,ru]
    font_size = 24
    onclick = hyprctl switchxkblayout all next

    position = 250, -20
    halign = center
    valign = center
}
