preload =   /home/portbound/Pictures/Wallpapers/arabian-desert-3440x1440-9503.jpg
wallpaper = DP-9, /home/portbound/Pictures/Wallpapers/arabian-desert-3440x1440-9503.jpg
wallpaper = DP-10, /home/portbound/Pictures/Wallpapers/arabian-desert-3440x1440-9503.jpg

preload =   /home/portbound/Pictures/Wallpapers/arabian-desert-1920x1200-9503.jpg
wallpaper = eDP-1, /home/portbound/Pictures/Wallpapers/arabian-desert-1920x1200-9503.jpg
