# preload =   /home/portbound/Pictures/Wallpapers/arabian-desert-3440x1440-9503.jpg
# wallpaper = DP-8, /home/portbound/Pictures/Wallpapers/arabian-desert-3440x1440-9503.jpg
# wallpaper = DP-9, /home/portbound/Pictures/Wallpapers/arabian-desert-3440x1440-9503.jpg
# wallpaper = DP-10, /home/portbound/Pictures/Wallpapers/arabian-desert-3440x1440-9503.jpg
# preload =   /home/portbound/Pictures/Wallpapers/valley_of_drakes.png
# wallpaper = DP-8, /home/portbound/Pictures/Wallpapers/valley_of_drakes.png
# wallpaper = DP-9, /home/portbound/Pictures/Wallpapers/valley_of_drakes.png
# wallpaper = DP-10, /home/portbound/Pictures/Wallpapers/valley_of_drakes.png

splash = false 
wallpaper {
		monitor = 
		path = /home/portbound/Pictures/Wallpapers/arabian-desert-3440x1440-9503.jpg
}

# preload =   /home/portbound/Pictures/Wallpapers/valley_of_drakes.png
# wallpaper = eDP-1, /home/portbound/Pictures/Wallpapers/valley_of_drakes.png
